# Supabase Configuration for Think Tank Technologies Installation Scheduler

[api]
# Port to use for the API URL (default: 54321)
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API endpoints.
# public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returns from a table or view. Limits payload size for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL (default: 54322)
port = 54322
# Port used by db diff command to initialize the shadow database.
shadow_port = 54320
# The database major version to use. This has to be the same as your remote database's. Run `SHOW server_version;` on the remote database to check.
major_version = 15

[studio]
enabled = true
# Port to use for Supabase Studio (default: 54323)
port = 54323
# External URL of the API server that frontend connects to (default: http://localhost:54321)
api_url = "http://localhost:54321"

# Email template used for sending the user invite email.
# `{{ .ConfirmationURL }}` placeholders are used by gotrue in the templates.
# Do not change the name of this file and the variable placeholders.
[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://thinktank-installation-scheduler-3uoj68q14.vercel.app"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
# refresh_token_rotation_enabled = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires refresh_token_rotation_enabled to be false.
# security_refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email addresses. 
# If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[edge_runtime]
enabled = true

[analytics]
enabled = false